server:
  port: 8080
  undertow:
    accesslog:
      enabled: true
      dir: ../logs
      pattern: common
      prefix: access_log
      suffix: .log
    io-threads: 4
    worker-threads: 32
    buffer-size: 1024
    direct-buffers: true

spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: ""
          url: jdbc:mysql://127.0.0.1:3306/test
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          username: root
          password: ""
          url: jdbc:mysql://127.0.0.1:3306/test1
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_2:
          username: root
          password: ""
          url: jdbc:mysql://127.0.0.1:3306/test2
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_3:
          username: root
          password: ""
          url: jdbc:mysql://127.0.0.1:3306/test3
          driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.yx: debug